import 'package:flutter/material.dart';

import 'description_models.dart';

final DescriptionBook parkinWorkinDescriptionBook = DescriptionBook(
  title: '앱에 대해 알아보기',
  subtitle: 'ParkinWorkin에서는 이하의 기능들을 제공합니다.',
  chapters: [
    DescriptionChapter(
      id: 'k',
      title: '워크플로우 관련',
      summary: '본 앱에서 제공하는 업무 프로세스들에 대한 약식 소개입니다.',
      sections: [
        DescriptionSection(
          id: 'k-01',
          title: '경량형 업무 화면',
          tocTitle: '경량형 업무 화면',
          eyebrow: '입차 완료, 출차 완료',
          summary: '',
          paragraphs: const [
            '주차장의 성격에 따라 제공되는 정산, 차량 정보  수정, 로그 확인 등의 기능이 제공됩니다',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '워크플로우 관련 00 캡처',
            caption: '워크플로우 관련 00에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.account_tree_rounded,
            assetPath: 'assets/description/workflow_01.png',
            slotName: 'assets/description/workflow_01.png',
          ),
        ),
        DescriptionSection(
          id: 'k-02',
          title: '표준형 업무 화면',
          tocTitle: '표준형 업무 화면',
          eyebrow: '입차 완료, 출차 요청, 출차 완료',
          summary: '',
          paragraphs: const [
            '주차장의 성격에 따라 제공되는 정산, 차량 정보  수정, 로그 확인 등의 기능이 제공됩니다',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '워크플로우 관련 02 캡처',
            caption: '워크플로우 관련 02에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.account_tree_rounded,
            assetPath: 'assets/description/workflow_02.png',
            slotName: 'assets/description/workflow_02.png',
          ),
        ),
        DescriptionSection(
          id: 'k-03',
          title: '심화형 업무 화면',
          tocTitle: '심화형 업무 화면',
          eyebrow: '입차 요청, 입차 완료, 출차 요청, 출차 완료',
          summary: '',
          paragraphs: const [
            '주차장의 성격에 따라 제공되는 정산, 차량 정보  수정, 로그 확인 등의 기능이 제공됩니다',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '워크플로우 관련 03 캡처',
            caption: '워크플로우 관련 03에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.account_tree_rounded,
            assetPath: 'assets/description/workflow_00.png',
            slotName: 'assets/description/workflow_00.png',
          ),
        ),
        DescriptionSection(
          id: 'h-01',
          title: '단순 출퇴근, 휴게시간 기록만',
          eyebrow: '',
          summary: '',
          paragraphs: const [
            '본 업무 화면은 단순 출퇴근 확인 및 업무 로그 기록 후, 통계 그래프 서비스 제공 등을 위한 프로세스입니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '싱글 모드 관련 캡처',
            caption: '싱글 모드 관련에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.looks_one_rounded,
            assetPath: 'assets/description/single_00.png',
            slotName: 'assets/description/single_00.png',
          ),
        ),
      ],
    ),
    DescriptionChapter(
      id: 'f',
      title: '입차 생성 관련',
      summary: '현장에서 신규 입차 건을 생성하고 필요한 입력값을 빠르게 확정하는 흐름입니다.',
      sections: [
        DescriptionSection(
          id: 'f-01',
          title: '번호판 자동 인식',
          tocTitle: 'Local OCR',
          eyebrow: 'Local OCR',
          summary: '',
          paragraphs: const [
            '번호판 입력 방법 중 하나로 먼저 화면 인식으로 번호판 데이터를 삽입할 수 있는 기능을 사용자에게 제공합니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '입차 생성 관련 01 캡처',
            caption: '입차 생성 관련 01에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.add_box_rounded,
            assetPath: 'assets/description/input_00.png',
            slotName: 'assets/description/input_00.png',
          ),
        ),
        DescriptionSection(
          id: 'f-02',
          title: '번호판 직접 입력',
          tocTitle: '번호판 직접 입력',
          eyebrow: '번호판 타이핑 기능',
          summary: '',
          paragraphs: const [
            'OCR을 생략하고, 사용자가 직접 입력할 수 있습니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '입차 생성 관련 02 캡처',
            caption: '입차 생성 관련 02에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.add_box_rounded,
            assetPath: 'assets/description/input_01.png',
            slotName: 'assets/description/input_01.png',
          ),
        ),
        DescriptionSection(
          id: 'f-03',
          title: '보조 기능 제공',
          tocTitle: '보조 기능 제공',
          eyebrow: '촬영, 구역 입력, 메모, 정산 유형 적용',
          summary: '',
          paragraphs: const [
            '입력하는 차량의 상태와 특이사항, 목적, 입차 여부 등 목적에 맞는 기능들을 제공합니다',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '입차 생성 관련 03 캡처',
            caption: '입차 생성 관련 03에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.add_box_rounded,
            assetPath: 'assets/description/input_02.png',
            slotName: 'assets/description/input_02.png',
          ),
        ),
        DescriptionSection(
          id: 'f-04',
          title: '주차 현황 실시간 확인',
          tocTitle: '주차 현황 실시간 확인',
          eyebrow: '영역이 아닌 단일 구역으로 지정',
          summary: '',
          paragraphs: const [
            '생성 페이지에서 구역 선택을 해야 할 경우, 현재 주차장의 컨디션을 시각화하여 제공합니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '입차 생성 관련 04 캡처',
            caption: '입차 생성 관련 04에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.add_box_rounded,
            assetPath: 'assets/description/input_03.png',
            slotName: 'assets/description/input_03.png',
          ),
        ),
        DescriptionSection(
          id: 'f-05',
          title: '주차장 변화 실시간 알림 제공',
          tocTitle: '주차장 변화 실시간 알림 제공',
          eyebrow: '로컬 알림',
          summary: '',
          paragraphs: const [
            '같은 지역에서 근무하고 있는 근무자 간 상호 알림으로 업무 현황 공유가 가능하며 핸드폰 절전 시에도 알람을 제공합니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '입차 생성 관련 05 캡처',
            caption: '입차 생성 관련 05에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.add_box_rounded,
            assetPath: 'assets/description/input_04.png',
            slotName: 'assets/description/input_04.png',
          ),
        ),
      ],
    ),
    DescriptionChapter(
      id: 'g',
      title: '주차 대기 중인 차량을 주차까지',
      summary: '요청으로 들어온 입차 건을 확인하고 상태를 이어서 처리하는 흐름입니다.',
      sections: [
        DescriptionSection(
          id: 'g-01',
          title: '진입 후 주차 대기 상태 차량 이동하기(1)',
          tocTitle: '진입 후 주차 대기 상태 차량 이동하기(1)',
          eyebrow: '테이블 모드',
          summary: '',
          paragraphs: const [
            '테이블 모드에서 수정하고자 하는 번호판을 선택하거나 스마트 검색을 통해 차량에 대한 상태를 수정할 수 있습니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '입차 요청 관련 01 캡처',
            caption: '입차 요청 관련 01에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.login_rounded,
            assetPath: 'assets/description/pr_request_000.png',
            slotName: 'assets/description/pr_request_000.png',
          ),
        ),
        DescriptionSection(
          id: 'g-001',
          title: '진입 후 주차 대기 상태 차량 이동하기(2)',
          tocTitle: '진입 후 주차 대기 상태 차량 이동하기(2)',
          eyebrow: '스마트 검색 모드',
          summary: '',
          paragraphs: const [
            '테이블 모드에서 수정하고자 하는 번호판을 선택하거나 스마트 검색을 통해 차량에 대한 상태를 수정할 수 있습니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '입차 요청 관련 01 캡처',
            caption: '입차 요청 관련 01에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.login_rounded,
            assetPath: 'assets/description/dr_request_000.png',
            slotName: 'assets/description/dr_request_000.png',
          ),
        ),
        DescriptionSection(
          id: 'g-02',
          title: '상세 정보 수정',
          tocTitle: '상세 정보 수정',
          eyebrow: '정보 확인, 주행 여부 알림',
          summary: '입차 요청 관련의 01페이지 요약입니다. 이 문구를 해당 화면의 핵심 기능 설명으로 교체하면 됩니다.',
          paragraphs: const [
            '현재 수정하고자 하는 차량의 기본 정보를 시각적으로 확인을 할 수 있으며 주행 중을 알리거나 곧바로 구역을 설정할 수 있습니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '입차 요청 관련 01 캡처',
            caption: '입차 요청 관련 01에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.login_rounded,
            assetPath: 'assets/description/pr_request_00.png',
            slotName: 'assets/description/pr_request_00.png',
          ),
        ),
        DescriptionSection(
          id: 'g-03',
          title: '부가 기능 제공',
          tocTitle: '부가 기능 제공',
          eyebrow: '정산 여부, 로그, 수정, 삭제',
          summary: '',
          paragraphs: const [
            '해당 차량에 대한 업무 기록 혹은 정산, 미비된 촬영, 삭제 등의 기능을 지원합니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '입차 요청 관련 02 캡처',
            caption: '입차 요청 관련 02에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.login_rounded,
            assetPath: 'assets/description/pr_request_01.png',
            slotName: 'assets/description/pr_request_01.png',
          ),
        ),
        DescriptionSection(
          id: 'g-03',
          title: '주행 중 기능 제공',
          tocTitle: '주행 중 기능 제공',
          eyebrow: '업무 중복 봉쇄',
          summary: '',
          paragraphs: const [
            '동일 지역의 특정 사용자가 주행 중을 시작하면 해당 번호판 차량에 대해 다른 사용자가 간섭을 할 수 없게 됩니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '입차 요청 관련 03 캡처',
            caption: '입차 요청 관련 03에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.login_rounded,
            assetPath: 'assets/description/pr_request_02.png',
            slotName: 'assets/description/pr_request_02.png',
          ),
        ),
        DescriptionSection(
          id: 'g-05',
          title: '현황 모드와 테이블 모드',
          tocTitle: '현황 모드와 테이블 모드',
          eyebrow: '3초 부재 시 현황 모드로 전환',
          summary: '',
          paragraphs: const [
            '3초 간 앱을 사용하지 않으면 자동으로 현황 모드로 전환되어 실시간 주차장 현황을 시각화합니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '입차 요청 관련 05 캡처',
            caption: '입차 요청 관련 05에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.login_rounded,
            assetPath: 'assets/description/pr_request_04.png',
            slotName: 'assets/description/pr_request_04.png',
          ),
        ),
      ],
    ),
    DescriptionChapter(
      id: 'c',
      title: '출차 완료 관련',
      summary: '출차가 완료된 이후 상태를 정리하고 기록을 마감하는 화면들입니다.',
      sections: [
        DescriptionSection(
          id: 'c-01',
          title: '차량에 대한 정산은 언제든 가능하도록',
          tocTitle: '차량에 대한 정산은 언제든 가능하도록',
          eyebrow: '정산 기능',
          summary: '',
          paragraphs: const [
            '정산되지 않은 차량은 출차 완료의 미정산 탭에 데이터가 남아 있으며 정산 유형이 없는 주차장의 경우, 영향을 받지 않습니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '출차 완료 관련 01 캡처',
            caption: '출차 완료 관련 01에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.task_alt_rounded,
            assetPath: 'assets/description/dc_completed_00.png',
            slotName: 'assets/description/dc_completed_00.png',
          ),
        ),
      ],
    ),
    DescriptionChapter(
      id: 'a',
      title: '정산 관련',
      summary: '금액 산정과 확인, 정산 완료 흐름을 이해하기 위한 섹션입니다.',
      sections: [
        DescriptionSection(
          id: 'a-01',
          title: '적용된 정산 유형 정보 확인법',
          tocTitle: '적용된 정산 유형 정보 확인법',
          eyebrow: '정산',
          summary: '정산 관련의 01페이지 요약입니다. 이 문구를 해당 화면의 핵심 기능 설명으로 교체하면 됩니다.',
          paragraphs: const [
            '필수로 정산을 해야 하는 주차장의 경우, 각 차량 별로 어떠한 정산 유형이 적용되어 있는 지 확인이 가능합니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '정산 관련 01 캡처',
            caption: '정산 관련 01에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.calculate_rounded,
            assetPath: 'assets/description/bill_00.png',
            slotName: 'assets/description/bill_00.png',
          ),
        ),
        DescriptionSection(
          id: 'a-02',
          title: '제공되는 정산 유형',
          tocTitle: '제공되는 정산 유형',
          eyebrow: '할증, 할인',
          summary: '',
          paragraphs: const [
            '사용자가 선택한 결제 방법에 대해서도 기록할 수 있으며, 할증, 할인 등의 여부도 실시간으로 계산한 금액 또한 확인이 가능합니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '정산 관련 02 캡처',
            caption: '정산 관련 02에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.calculate_rounded,
            assetPath: 'assets/description/bill_01.png',
            slotName: 'assets/description/bill_01.png',
          ),
        ),
        DescriptionSection(
          id: 'a-04',
          title: '정산 금액 확인',
          tocTitle: '정산 금액 확인',
          eyebrow: '최종 정산 금액 확인',
          summary: '',
          paragraphs: const [
            '정산 시간을 기준으로 계산된 금액을 확인할 수 있습니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '정산 관련 04 캡처',
            caption: '정산 관련 04에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.calculate_rounded,
            assetPath: 'assets/description/bill_03.png',
            slotName: 'assets/description/bill_03.png',
          ),
        ),
        DescriptionSection(
          id: 'a-05',
          title: '정산 취소',
          tocTitle: '정산 취소',
          eyebrow: '정산 무효화',
          summary: '',
          paragraphs: const [
            '정산했던 차량에 대해서 정산을 취소할 수 있습니다. 이후 다시 정산을 할 경우, 정산한 시간을 기준으로 다시 계산됩니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '정산 관련 05 캡처',
            caption: '정산 관련 05에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.calculate_rounded,
            assetPath: 'assets/description/bill_04.png',
            slotName: 'assets/description/bill_04.png',
          ),
        ),
      ],
    ),
    DescriptionChapter(
      id: 'l',
      title: '월 주차 관련',
      summary: '월 단위 집계와 확인에 필요한 정산 화면을 순서대로 살펴보는 구성입니다.',
      sections: [
        DescriptionSection(
          id: 'l-01',
          title: '월 주차 관리(1)',
          tocTitle: '월 주차 관리(1)',
          eyebrow: '월 주차 등록 및 관리',
          summary: '',
          paragraphs: const [
            '월 주차, 정기 차량의 경우, 사용자의 요구사항에 맞춰 차량에 대한 정기 주차를 지정할 수 있습니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '월정산 관련 01 캡처',
            caption: '월정산 관련 01에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.calendar_month_rounded,
            assetPath: 'assets/description/monthly_00.png',
            slotName: 'assets/description/monthly_00.png',
          ),
        ),
        DescriptionSection(
          id: 'l-02',
          title: '월 주차 관리(2)',
          tocTitle: '월 주차 관리(2)',
          eyebrow: '차량 관리',
          summary: '',
          paragraphs: const [
            '정기 차량의 경우, 차량 생성 페이지에서 자동으로 무료 차량으로 인식합니다. 필요한 정보에 따라 칩을 선택해 마감 기한, 메모 여부 등도 확인이 가능합니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '월정산 관련 02 캡처',
            caption: '월정산 관련 02에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.calendar_month_rounded,
            assetPath: 'assets/description/monthly_01.png',
            slotName: 'assets/description/monthly_01.png',
          ),
        ),
        DescriptionSection(
          id: 'l-04',
          title: '월 주차 관리(3)',
          tocTitle: '월 주차 관리(3)',
          eyebrow: '정기 주차 갱신',
          summary: '',
          paragraphs: const [
            '정기 차량에 대한 결제 정보와 자동 갱신등을 관리하여 기록을 남길 수 있습니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '월정산 관련 04 캡처',
            caption: '월정산 관련 04에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.calendar_month_rounded,
            assetPath: 'assets/description/monthly_03.png',
            slotName: 'assets/description/monthly_03.png',
          ),
        ),
      ],
    ),
    DescriptionChapter(
      id: 'b',
      title: '대시보드 관련',
      summary: '운영 현황과 주요 지표를 한눈에 파악하는 대시보드 화면들입니다.',
      sections: [
        DescriptionSection(
          id: 'b-01',
          title: '대시보드',
          tocTitle: '대시보드',
          eyebrow: '휴게시간, 퇴근, 사진 전송, 기타 서류',
          summary:
              '각 사용자들은 휴게시간을 1회 가져야 퇴근을 누를 수 있습니다. 휴게시간을 가지지 않는 업무의 경우에도 명시적인 절차는 진행해야 합니다.',
          paragraphs: const [
            '또한 사용자는 사고 등의 이슈로 촬영한 사진을 전송할 때, 앨범에서 공유할 필요 없이 사진 전송 버튼으로 원패턴 프로세스가 가능합니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '대시보드 관련 01 캡처',
            caption: '대시보드 관련 01에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.space_dashboard_rounded,
            assetPath: 'assets/description/dashboard_00.png',
            slotName: 'assets/description/dashboard_00.png',
          ),
        ),
        DescriptionSection(
          id: 'b-02',
          title: '기타 서류',
          tocTitle: '기타 서류',
          eyebrow: '출퇴근, 휴게시간, 업무 보고',
          summary: '사용자는 출퇴근과 휴게시간을 주기적으로 제출해야 관리자가 기록을 확인할 수 있습니다.',
          paragraphs: const [
            '업무 시작, 종료 보고서는 팀장 이상 급의 직군에게만 노출 시킬 수 있습니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '대시보드 관련 02 캡처',
            caption: '대시보드 관련 02에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.space_dashboard_rounded,
            assetPath: 'assets/description/dashboard_01.png',
            slotName: 'assets/description/dashboard_01.png',
          ),
        ),
      ],
    ),
    DescriptionChapter(
      id: 'e',
      title: '본사 관련',
      summary: '현장 이후 운영 관리와 본사 화면을 통해 확인하는 기능들입니다.',
      sections: [
        DescriptionSection(
          id: 'e-01',
          title: '본사 업무',
          tocTitle: '본사 업무',
          eyebrow: '실시간 관리',
          summary: '본사 직원 혹은 관리자에게는 전용 UI가 제공됩니다.',
          paragraphs: const [
            '기본적인 각 근무지 별 업무 현황부터 상세 본사 업무까지 패널을 지원합니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '본사 관련 01 캡처',
            caption: '본사 관련 01에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.apartment_rounded,
            assetPath: 'assets/description/hq_00.png',
            slotName: 'assets/description/hq_00.png',
          ),
        ),
        DescriptionSection(
          id: 'e-02',
          title: '상세 관리 업무',
          tocTitle: '상세 관리 업무',
          eyebrow: '각종 업무 보조 수단 지원',
          summary: '본사 관련의 02페이지 요약입니다. 이 문구를 해당 화면의 핵심 기능 설명으로 교체하면 됩니다.',
          paragraphs: const [
            'Google Calendar를 연동하여 관리자 간 업무 공유부터 근무자들의 출퇴근, 휴게시간 관리 및 서류화를 지원합니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '본사 관련 02 캡처',
            caption: '본사 관련 02에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.apartment_rounded,
            assetPath: 'assets/description/hq_01.png',
            slotName: 'assets/description/hq_01.png',
          ),
        ),
        DescriptionSection(
          id: 'e-05',
          title: '플로팅 기능 지원',
          tocTitle: '플로팅 기능 지원',
          eyebrow: '업무 중 관리 업무 병행 가능',
          summary: '본사 상세 화면의 상단 Bubble 스위치를 제공합니다.',
          paragraphs: const [
            '불가피한 현장 업무 중 관리직의 역할을 수행해야 할 경우, 플로팅 UI 기능을 통해 원터치 병행 기능 또한 지원하고 있습니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '본사 관련 05 캡처',
            caption: '본사 관련 05에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.apartment_rounded,
            assetPath: 'assets/description/hq_04.png',
            slotName: 'assets/description/hq_04.png',
          ),
        ),
      ],
    ),
    DescriptionChapter(
      id: 'i',
      title: '태블릿 모드 관련',
      summary: '가로 화면 기반으로 운영되는 태블릿 모드 전용 소개 섹션입니다.',
      sections: [
        DescriptionSection(
          id: 'i-01',
          title: '내방객 서비스 지원',
          tocTitle: '내방객 서비스 지원',
          eyebrow: '내방객을 위한 기능',
          summary: '태블릿 모드 관련의 01페이지 요약입니다. 이 문구를 해당 화면의 핵심 기능 설명으로 교체하면 됩니다.',
          paragraphs: const [
            '사용자의 요구사항에 맞춰 내방객 혹은 고객사도 특정 차량에 대한 출차 요청 기능을 제공할 수 있습니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.landscape,
          media: const DescriptionMediaSpec(
            title: '태블릿 모드 관련 01 캡처',
            caption: '태블릿 모드 관련 01에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.tablet_mac_rounded,
            assetPath: 'assets/description/tablet_01.png',
            slotName: 'assets/description/tablet_01.png',
          ),
        ),
        DescriptionSection(
          id: 'i-02',
          title: '큰 패드 모드',
          tocTitle: '큰 패드 모드',
          eyebrow: '출차 요청 뒷 번호, 검색 기능',
          summary: '',
          paragraphs: const [
            '고객이 직접 출차 요청을 할 수 있도록 하며 현재 출차 요청 현황을 시각화해주는 기능입니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.landscape,
          media: const DescriptionMediaSpec(
            title: '태블릿 모드 관련 02 캡처',
            caption: '태블릿 모드 관련 02에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.tablet_mac_rounded,
            assetPath: 'assets/description/tablet_02.png',
            slotName: 'assets/description/tablet_02.png',
          ),
        ),
        DescriptionSection(
          id: 'i-03',
          title: '작은 패드 모드',
          tocTitle: '작은 패드 모드',
          eyebrow: '작은 태블릿 최적화',
          summary: '태블릿 모드 관련의 03페이지 요약입니다. 이 문구를 해당 화면의 핵심 기능 설명으로 교체하면 됩니다.',
          paragraphs: const [
            '비치한 태블릿의 크기가 작아 큰 패드의 사용이 부적합한 경우를 위해 제공하는 기능입니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.landscape,
          media: const DescriptionMediaSpec(
            title: '태블릿 모드 관련 03 캡처',
            caption: '태블릿 모드 관련 03에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.tablet_mac_rounded,
            assetPath: 'assets/description/tablet_03.png',
            slotName: 'assets/description/tablet_03.png',
          ),
        ),
        DescriptionSection(
          id: 'i-04',
          title: '직접 출차 모드',
          tocTitle: '직접 출차 모드',
          eyebrow: '1:1 고객 관리',
          summary: '',
          paragraphs: const [
            'VIP 등, 고객사의 직원이 직접 출차 요청을 해야하는 기능을 위해 태블릿, 핸드폰 모두 지원하는 기능입니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.landscape,
          media: const DescriptionMediaSpec(
            title: '태블릿 모드 관련 04 캡처',
            caption: '태블릿 모드 관련 04에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.tablet_mac_rounded,
            assetPath: 'assets/description/tablet_00.png',
            slotName: 'assets/description/tablet_00.png',
          ),
        ),
        DescriptionSection(
          id: 'i-05',
          title: '뷰 모드',
          tocTitle: '뷰 모드',
          eyebrow: '단순 시각화',
          summary: '',
          paragraphs: const [
            '고객에게 출차 요청 상태가 된 차량들의 번호판 현황만 출력해주는 모드입니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.landscape,
          media: const DescriptionMediaSpec(
            title: '태블릿 모드 관련 05 캡처',
            caption: '태블릿 모드 관련 05에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.tablet_mac_rounded,
            assetPath: 'assets/description/tablet_04.png',
            slotName: 'assets/description/tablet_04.png',
          ),
        ),
        DescriptionSection(
          id: 'i-06',
          title: '2D 맵 모드',
          tocTitle: '2D 맵 모드',
          eyebrow: '2D 시각화',
          summary: '',
          paragraphs: const [
            '사용자에게 현재 주차 구역 별 주차 현황과 잔여 주차 구역을 시각화하고, 출차 요청 기능을 지원합니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.landscape,
          media: const DescriptionMediaSpec(
            title: '태블릿 모드 관련 06 캡처',
            caption: '태블릿 모드 관련 06에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.tablet_mac_rounded,
            assetPath: 'assets/description/tablet_05.png',
            slotName: 'assets/description/tablet_05.png',
          ),
        ),
        DescriptionSection(
          id: 'i-07',
          title: '3D 맵 모드',
          tocTitle: '3D 맵 모드',
          eyebrow: '3D 모델링',
          summary: '',
          paragraphs: const [
            '현재 주차 구역을 3D로 모델링을 하여 시각화 이벤트를 제공합니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.landscape,
          media: const DescriptionMediaSpec(
            title: '태블릿 모드 관련 07 캡처',
            caption: '태블릿 모드 관련 07에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.tablet_mac_rounded,
            assetPath: 'assets/description/tablet_06.png',
            slotName: 'assets/description/tablet_06.png',
          ),
        ),
      ],
    ),
    DescriptionChapter(
      id: 'j',
      title: '태블릿 요청 관련',
      summary: '태블릿 환경에서 요청을 확인하고 처리하는 흐름을 가로 화면 기준으로 보여줍니다.',
      sections: [
        DescriptionSection(
          id: 'j-01',
          title: '태블릿으로 출차 요청(1)',
          tocTitle: '태블릿으로 출차 요청(1)',
          eyebrow: '태블릿 사용',
          summary: '',
          paragraphs: const [
            '태블릿으로 출차 요청을 진행할 시, 이중 체크로 실수를 방지합니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.landscape,
          media: const DescriptionMediaSpec(
            title: '태블릿 요청 관련 01 캡처',
            caption: '태블릿 요청 관련 01에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.touch_app_rounded,
            assetPath: 'assets/description/tablet_request_00.png',
            slotName: 'assets/description/tablet_request_00.png',
          ),
        ),
        DescriptionSection(
          id: 'j-02',
          title: '태블릿으로 출차 요청(2)',
          tocTitle: '태블릿으로 출차 요청(2)',
          eyebrow: '안내 팝업',
          summary: '',
          paragraphs: const [
            '출차 요청에 성공했을 경우, 안내 팝업으로 현재 구역과 멘트를 사용자에게 제공할 수 있습니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.landscape,
          media: const DescriptionMediaSpec(
            title: '태블릿 요청 관련 02 캡처',
            caption: '태블릿 요청 관련 02에 대응하는 화면 캡처 이미지입니다.',
            icon: Icons.touch_app_rounded,
            assetPath: 'assets/description/tablet_request_01.png',
            slotName: 'assets/description/tablet_request_01.png',
          ),
        ),
      ],
    ),
    DescriptionChapter(
      id: 'closing',
      title: '문의',
      summary: '문의 관련 페이지.',
      sections: [
        DescriptionSection(
          id: 'closing-01',
          title: '문의 사항',
          eyebrow: '',
          summary: 'qperfectusofficial@gmail.com',
          paragraphs: const [
            '메일로 문의를 주시면 더 자세한 안내를 받아보실 수 있습니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.textOnly,
          media: const DescriptionMediaSpec(
            title: '마무리',
            caption: '이 페이지는 텍스트만 사용합니다.',
            icon: Icons.flag_rounded,
          ),
        ),
      ],
    ),
  ],
);
