import 'package:flutter/material.dart';

import 'description_models.dart';

final DescriptionBook parkinWorkinDescriptionBook = DescriptionBook(
  title: '앱에 대해 알아보기',
  subtitle:
      'ParkinWorkin에서는 현장 주차 운영, 근태, 정산, 본사 관리, 태블릿 고객 요청까지 연결된 기능들을 제공합니다.',
  chapters: [
    DescriptionChapter(
      id: 'workflow',
      title: '업무 모드, 대시보드, 근태 관리',
      summary: '현장 성격에 따라 달라지는 업무 화면과 출퇴근, 휴게, 사진 전송, 문서 진입 흐름입니다.',
      sections: [
        DescriptionSection(
          id: 'workflow-01',
          title: '경량형 업무 화면',
          tocTitle: '경량형 업무 화면',
          eyebrow: '입차 완료, 출차 완료',
          summary: '경량형은 저비용 이용자들을 위한 상품으로 입차 완료와 출차 완료만을 통해 단순 업무를 처리합니다.',
          paragraphs: const [
            '주차장 규모나 운영 방식이 단순한 경우 권장합니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '경량형 업무 화면 캡처',
            caption: '경량형 업무 화면 화면에 대응하는 캡처 이미지입니다.',
            icon: Icons.account_tree_rounded,
            assetPath: 'assets/description/workflow_01.png',
            slotName: 'assets/description/workflow_01.png',
          ),
        ),
        DescriptionSection(
          id: 'workflow-02',
          title: '기본형 업무 화면',
          tocTitle: '기본형 업무 화면',
          eyebrow: '입차 완료, 출차 요청, 출차 완료',
          summary: '기본형 현장은 경량형 모드에 출차 주행 옵션을 추가한 보편적인 업무 형태입니다.',
          paragraphs: const [
            '일반적인 업무 형태에 권장합니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '기본형 업무 화면 캡처',
            caption: '기본형 업무 화면 화면에 대응하는 캡처 이미지입니다.',
            icon: Icons.account_tree_rounded,
            assetPath: 'assets/description/workflow_02.png',
            slotName: 'assets/description/workflow_02.png',
          ),
        ),
        DescriptionSection(
          id: 'workflow-03',
          title: '확장형 업무 화면',
          tocTitle: '확장형 업무 화면',
          eyebrow: '입차 요청, 입차 완료, 출차 요청, 출차 완료',
          summary: '확장형 현장은 차량 진입 직후 대기 상태부터 출차 완료까지 발렛 업무의 모든 부분을 관리합니다.',
          paragraphs: const [
            '입차 요청으로 들어온 차량을 확인하고, 구역 지정과 주차 완료를 거쳐 출차 요청과 완료까지 연결합니다.',
            '업무가 많은 현장에서는 상태를 세분화해 여러 근무자가 동시에 작업하더라도 차량 운행 단계와 주차 흐름을 명확하게 유지할 수 있습니다.',
          ],
          bullets: const [
            '업무가 많은 현장에서는 상태를 세분화해 여러 근무자가 동시에 주차 업무를 수행하는 경우에 권장합니다.',
          ],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '확장형 업무 화면 캡처',
            caption: '확장형 업무 화면 화면에 대응하는 캡처 이미지입니다.',
            icon: Icons.account_tree_rounded,
            assetPath: 'assets/description/workflow_03.png',
            slotName: 'assets/description/workflow_03.png',
          ),
        ),
        DescriptionSection(
          id: 'workflow-04',
          title: '출퇴근 기록형',
          tocTitle: '출퇴근 기록형',
          eyebrow: '출퇴근, 휴게, 업무 로그',
          summary: '차량 업무를 배제하고, 출퇴근 확인, 휴게시간 기록, 통계가 중요한 현장에 맞춘 단순 업무 모드입니다.',
          paragraphs: const [
            '출근, 휴게, 퇴근, 통계 관리 등 노무 및 본사 업무 중심으로 구성됩니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '출퇴근 기록형 캡처',
            caption: '출퇴근 기록형 화면에 대응하는 캡처 이미지입니다.',
            icon: Icons.looks_one_rounded,
            assetPath: 'assets/description/workflow_04.jpg',
            slotName: 'assets/description/workflow_04.jpg',
          ),
        ),
      ],
    ),
    DescriptionChapter(
      id: 'input',
      title: '입차 생성, 촬영, OCR',
      summary: '신규 차량을 등록하고 번호판, 사진, 구역, 메모, 정산 유형을 확정하는 흐름입니다.',
      sections: [
        DescriptionSection(
          id: 'input-01',
          title: '번호판 자동 인식',
          tocTitle: 'OCR',
          eyebrow: '카메라, 화면 인식, 번호판 후보',
          summary: 'OCR을 이용해 번호판을 자동으로 읽고 차량 등록 입력값으로 사용할 수 있습니다.',
          paragraphs: const [
            '사용자는 번호판을 직접 입력하기 전 카메라 인식으로 번호판 데이터를 삽입할 수 있습니다.',
          ],
          bullets: const [
            '자동 인식 결과를 사용자가 바로 보정하고, 이후 OCR에 반영시킬 수 있습니다.',
          ],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '번호판 자동 인식 캡처',
            caption: '번호판 자동 인식 화면에 대응하는 캡처 이미지입니다.',
            icon: Icons.add_box_rounded,
            assetPath: 'assets/description/input_01.png',
            slotName: 'assets/description/input_01.png',
          ),
        ),
        DescriptionSection(
          id: 'input-02',
          title: '번호판 직접 입력',
          tocTitle: '직접 입력',
          eyebrow: '번호판 타이핑, 한글 키패드',
          summary: 'OCR을 생략하거나 보정해야 할 때 사용자가 번호판을 직접 입력합니다.',
          paragraphs: const [
            '직접 입력 화면은 차량번호 형식에 맞춰 빠르게 번호와 한글 문자를 넣을 수 있도록 구성됩니다.',
            '현장에서 번호판이 가려졌거나 OCR 결과가 불확실한 경우에도 수동 입력으로 업무를 이어갈 수 있습니다.',
          ],
          bullets: const [
            'OCR 없이 신규 차량을 생성할 수 있습니다.',
            '번호판 뒤 4자리와 전체 번호 입력을 업무 흐름에 맞게 지원합니다.',
          ],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '번호판 직접 입력 캡처',
            caption: '번호판 직접 입력 화면에 대응하는 캡처 이미지입니다.',
            icon: Icons.edit_rounded,
            assetPath: 'assets/description/input_02.png',
            slotName: 'assets/description/input_02.png',
          ),
        ),
        DescriptionSection(
          id: 'input-03',
          title: '차량 데이터 구체화',
          tocTitle: '데이터 구체화',
          eyebrow: '구역, 메모, 목적, 정산 유형, 차량 사진 촬영',
          summary:
              '차량 생성 시 차량 상태와 특이사항, 정산 유형, 구역 정보, 차량 사진 촬영 정보들을 함께 입력합니다.',
          paragraphs: const [
            '입력 페이지는 번호판만 저장하는 것이 아니라 현장 업무에 필요한 구역, 위치, 메모, 차량 상태, 입차 여부, 정산 유형을 함께 다룹니다.',
            '정기 차량이나 무료 차량처럼 현장 정책에 따라 다른 처리가 필요한 차량도 생성 단계에서 구분할 수 있습니다.',
          ],
          bullets: const [
            '차량 상태와 특이사항을 메모로 남깁니다.',
            '현장에 맞는 정산 유형과 구역 정보를 함께 선택합니다.',
          ],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '입차 보조 입력 캡처',
            caption: '입차 보조 입력 화면에 대응하는 캡처 이미지입니다.',
            icon: Icons.tune_rounded,
            assetPath: 'assets/description/input_03.png',
            slotName: 'assets/description/input_03.png',
          ),
        ),
      ],
    ),
    DescriptionChapter(
      id: 'plate_flow',
      title: '차량 상태 처리와 실시간 업무 흐름',
      summary:
          '입차 요청부터 입차 완료, 출차 요청, 출차 완료, 검색, 잠금, 로그까지 차량 상태를 처리하는 핵심 흐름입니다.',
      sections: [
        DescriptionSection(
          id: 'plate-flow-01',
          title: '차량 상세 정보 수정',
          tocTitle: '상세 수정',
          eyebrow: '정보 확인, 구역 설정, 주행 알림',
          summary: '선택한 차량의 기본 정보와 상태를 확인하고 구역, 위치, 메모, 주행 여부를 수정합니다.',
          paragraphs: const [
            '상세 화면은 번호판, 등록 시각, 차량 이미지, 구역, 위치, 상태 태그, 정산 정보, 메모를 한 곳에서 확인하도록 제공합니다.',
            '근무자는 필요할 때 곧바로 구역을 지정하거나 차량을 이동 중으로 표시해 다른 작업자와 상태를 공유할 수 있습니다.',
          ],
          bullets: const [
            '차량 정보와 업무 상태를 시각적으로 확인합니다.',
            '구역 설정과 주행 중 표시를 상세 화면에서 처리합니다.',
          ],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '차량 상세 정보 수정 캡처',
            caption: '차량 상세 정보 수정 화면에 대응하는 캡처 이미지입니다.',
            icon: Icons.edit_note_rounded,
            assetPath: 'assets/description/plate_flow_01.png',
            slotName: 'assets/description/plate_flow_01.png',
          ),
        ),
        DescriptionSection(
          id: 'plate-flow-02',
          title: '번호판 뒤 4자리 검색',
          tocTitle: '뒤 4자리 검색',
          eyebrow: '검색 결과, 출차 완료 로그, 상태 구분',
          summary: '고객이 번호 전체를 모르는 경우에도 뒤 4자리로 차량과 과거 완료 로그를 검색할 수 있습니다.',
          paragraphs: const [
            '차량 목록이 많은 현장에서는 번호판 뒤 4자리 검색이 가장 빠른 접근 방법이 됩니다.',
            '검색 결과는 현재 차량과 출차 완료 로그를 구분해 보여줄 수 있어 이미 처리된 차량인지도 확인할 수 있습니다.',
          ],
          bullets: const [
            '번호판 뒤 4자리로 후보 차량을 찾습니다.',
            '현재 차량과 완료 로그를 분리해 혼선을 줄입니다.',
          ],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '번호판 뒤 4자리 검색 캡처',
            caption: '번호판 뒤 4자리 검색 화면에 대응하는 캡처 이미지입니다.',
            icon: Icons.manage_search_rounded,
            assetPath: 'assets/description/plate_flow_02.png',
            slotName: 'assets/description/plate_flow_02.png',
          ),
        ),
        DescriptionSection(
          id: 'plate-flow-03',
          title: '출차 완료 로그 검색',
          tocTitle: '출차 완료 로그 검색',
          eyebrow: '로그 검색',
          summary: '차량 뒷 4자리를 검색하여 언제 해당 차량이 들어오고 나갔는지를 표적 검색할 수 있습니다.',
          paragraphs: const [
            '차량의 입차 시간, 출차 시간만 간략하게 정보를 확인할 때 이용하는 기능입니다.',
          ],
          bullets: const [],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '번호판 업무 로그 캡처',
            caption: '번호판 업무 로그 화면에 대응하는 캡처 이미지입니다.',
            icon: Icons.receipt_long_rounded,
            assetPath: 'assets/description/plate_flow_03.jpg',
            slotName: 'assets/description/plate_flow_03.jpg',
          ),
        ),
        DescriptionSection(
          id: 'plate-flow-04',
          title: '출차 완료와 미정산 차량',
          tocTitle: '출차 완료',
          eyebrow: '완료 기록, 미정산 탭, 후정산',
          summary: '출차 완료된 차량 중 정산되지 않은 차량은 별도 탭에 남아 이후에도 정산할 수 있습니다.',
          paragraphs: const [
            '정산이 필수인 주차장에서는 차량이 출차 완료되어도 정산이 끝나지 않았다면 미정산 상태로 남습니다.',
            '정산 유형이 없는 주차장에서는 이 흐름의 영향을 받지 않도록 설계되어 현장 정책에 따라 다르게 동작합니다.',
          ],
          bullets: const [
            '출차 완료 후에도 미정산 차량을 추적합니다.',
            '정산이 없는 현장은 제한 없이 사용할 수 있습니다.',
          ],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '출차 완료와 미정산 차량 캡처',
            caption: '출차 완료와 미정산 차량 화면에 대응하는 캡처 이미지입니다.',
            icon: Icons.task_alt_rounded,
            assetPath: 'assets/description/plate_flow_04.png',
            slotName: 'assets/description/plate_flow_04.png',
          ),
        ),
      ],
    ),
    DescriptionChapter(
      id: 'billing_monthly',
      title: '정산과 월주차',
      summary: '시간 요금, 할증·할인, 결제수단, 정산 취소, 월주차 등록과 갱신을 다루는 기능입니다.',
      sections: [
        DescriptionSection(
          id: 'billing-01',
          title: '적용된 정산 유형 확인',
          tocTitle: '정산 유형 확인',
          eyebrow: '정산 유형, 차량별 요금 기준',
          summary: '정산이 필요한 주차장에서는 차량마다 어떤 정산 유형이 적용되어 있는지 확인할 수 있습니다.',
          paragraphs: const [
            '각 차량은 현장 설정과 입력값에 따라 기본 요금, 고정 요금, 무료 처리, 월주차 여부 같은 정산 기준을 가질 수 있습니다.',
            '근무자는 차량 상세 또는 정산 화면에서 적용된 유형을 확인한 뒤 금액을 계산하고 결제 처리를 진행합니다.',
          ],
          bullets: const [
            '차량별 정산 유형을 화면에서 확인합니다.',
            '정산이 필수인 현장과 아닌 현장을 구분합니다.',
          ],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '적용된 정산 유형 확인 캡처',
            caption: '적용된 정산 유형 확인 화면에 대응하는 캡처 이미지입니다.',
            icon: Icons.calculate_rounded,
            assetPath: 'assets/description/billing_01.png',
            slotName: 'assets/description/billing_01.png',
          ),
        ),
        DescriptionSection(
          id: 'billing-02',
          title: '결제 방법과 할증·할인',
          tocTitle: '할증과 할인',
          eyebrow: '결제수단, 할인, 할증, 실시간 계산',
          summary: '사용자가 선택한 결제 방법을 기록하고 할인·할증 적용 후 실시간 금액을 확인합니다.',
          paragraphs: const [
            '결제수단은 차량 정산 이력에 남아 추후 로그와 통계에서 확인할 수 있습니다.',
            '할인 또는 추가 요금이 필요한 경우 정산 화면에서 금액이 다시 계산되어 최종 결제 금액으로 반영됩니다.',
          ],
          bullets: const [
            '결제수단을 차량 정산 기록에 저장합니다.',
            '할증과 할인 적용 결과를 실시간으로 확인합니다.',
          ],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '결제 방법과 할증·할인 캡처',
            caption: '결제 방법과 할증·할인 화면에 대응하는 캡처 이미지입니다.',
            icon: Icons.payments_rounded,
            assetPath: 'assets/description/billing_02.png',
            slotName: 'assets/description/billing_02.png',
          ),
        ),
        DescriptionSection(
          id: 'billing-03',
          title: '정산 금액 확인',
          tocTitle: '금액 확인',
          eyebrow: '정산 시각, 최종 금액',
          summary: '정산 시간을 기준으로 계산된 금액과 최종 결제 금액을 확인합니다.',
          paragraphs: const [
            '요금은 입차 시각, 정산 시각, 현장 요금 정책, 추가 보정값에 따라 계산됩니다.',
            '근무자는 최종 금액을 확인한 뒤 정산 완료를 기록하고 출차 흐름을 이어갈 수 있습니다.',
          ],
          bullets: const [
            '정산 시각 기준으로 금액을 계산합니다.',
            '최종 결제 전 금액을 확인하는 단계를 제공합니다.',
            '정산 취소 후, 재정산도 가능합니다.'
          ],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '정산 금액 확인 캡처',
            caption: '정산 금액 확인 화면에 대응하는 캡처 이미지입니다.',
            icon: Icons.price_check_rounded,
            assetPath: 'assets/description/billing_03.png',
            slotName: 'assets/description/billing_03.png',
          ),
        ),
        DescriptionSection(
          id: 'monthly-01',
          title: '월주차 등록과 관리',
          tocTitle: '월주차 등록',
          eyebrow: '정기 차량, 무료 차량, 우선순위',
          summary: '월주차 또는 정기 차량을 등록하고 차량별 정기 주차 조건과 우선순위를 관리합니다.',
          paragraphs: const [
            '정기 차량은 일반 차량과 다르게 무료 또는 별도 정산 조건으로 처리될 수 있습니다.',
            '차량 생성 시 월주차 목록과 매칭되면 자동으로 무료 차량이나 정기 차량으로 인식해 현장 업무 실수를 줄입니다.',
          ],
          bullets: const [
            '정기 차량을 월주차 목록으로 관리합니다.',
            '입차 생성 시 월주차 차량을 자동으로 식별할 수 있습니다.',
          ],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '월주차 등록과 관리 캡처',
            caption: '월주차 등록과 관리 화면에 대응하는 캡처 이미지입니다.',
            icon: Icons.calendar_month_rounded,
            assetPath: 'assets/description/monthly_01.png',
            slotName: 'assets/description/monthly_01.png',
          ),
        ),
        DescriptionSection(
          id: 'monthly-02',
          title: '정기 주차 갱신과 결제 내역',
          tocTitle: '월주차 갱신',
          eyebrow: '갱신, 결제 정보, 연장 기록',
          summary: '정기 차량의 결제 정보와 자동 갱신, 연장 기록을 관리해 월주차 이력을 남깁니다.',
          paragraphs: const [
            '월주차 차량은 결제일, 갱신일, 만료일, 연장 여부를 기록하며 이 정보는 현장 차량 생성과 정산 판단에 영향을 줍니다.',
            '갱신 기록을 남기면 관리자는 어떤 차량이 언제 연장되었는지 확인하고 누락 결제를 추적할 수 있습니다.',
          ],
          bullets: const [
            '정기권 연장과 결제 기록을 차량별로 관리합니다.',
            '자동 갱신 여부와 만료일을 업무 판단에 사용합니다.',
          ],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '정기 주차 갱신과 결제 내역 캡처',
            caption: '정기 주차 갱신과 결제 내역 화면에 대응하는 캡처 이미지입니다.',
            icon: Icons.update_rounded,
            assetPath: 'assets/description/monthly_02.png',
            slotName: 'assets/description/monthly_02.png',
          ),
        ),
      ],
    ),
    DescriptionChapter(
      id: 'documents',
      title: '문서, 보고서, 전자서명',
      summary: '업무 시작·종료 보고서, 마감 처리, 경위서, 연차·결근 신청서, PDF·Excel 발송을 다룹니다.',
      sections: [
        DescriptionSection(
          id: 'docs-01',
          title: '업무 시작과 종료 보고서',
          tocTitle: '업무 보고서',
          eyebrow: '출퇴근, 휴게, 업무 보고',
          summary: '근무자는 업무 시작과 종료 시 필요한 보고서를 작성하고 관리자는 이를 확인합니다.',
          paragraphs: const [
            '보고서는 단순 근태 버튼과 달리 현장 상태, 특이사항, 담당자 확인 같은 서류성 정보를 담을 수 있습니다.',
            '팀장 이상 또는 권한이 있는 사용자에게만 노출되도록 역할 기반 표시가 적용될 수 있습니다.',
          ],
          bullets: const [
            '업무 시작·종료 보고서를 앱에서 작성합니다.',
            '권한에 따라 보고서 버튼과 문서가 노출됩니다.',
          ],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '업무 시작과 종료 보고서 캡처',
            caption: '업무 시작과 종료 보고서 화면에 대응하는 캡처 이미지입니다.',
            icon: Icons.assignment_rounded,
            assetPath: 'assets/description/docs_01.jpg',
            slotName: 'assets/description/docs_01.jpg',
          ),
        ),
      ],
    ),
    DescriptionChapter(
      id: 'headquarter',
      title: '본사, 관리자',
      summary:
          '본사 전용 UI, 근무지 현황, 메모, Google Calendar, 출근부, 통계, 로드맵을 제공하는 관리 기능입니다.',
      sections: [
        DescriptionSection(
          id: 'hq-01',
          title: '본사 업무 화면',
          tocTitle: '본사 업무',
          eyebrow: '실시간 관리, 관리자 UI',
          summary: '본사 직원 또는 관리자에게는 현장별 업무 현황과 상세 관리 기능을 볼 수 있는 전용 UI가 제공됩니다.',
          paragraphs: const [
            '본사 화면은 각 근무지의 차량 현황, 근태, 문서, 메모, 통계 같은 관리 정보를 모아 보여줍니다.',
            '현장 이후의 운영 관리와 관리자 판단에 필요한 패널을 별도로 제공해 일반 현장 화면과 역할을 구분합니다.',
          ],
          bullets: const [
            '본사용 전용 관리 UI를 제공합니다.',
            '여러 근무지의 업무 현황을 확인할 수 있습니다.',
          ],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '본사 업무 화면 캡처',
            caption: '본사 업무 화면 화면에 대응하는 캡처 이미지입니다.',
            icon: Icons.apartment_rounded,
            assetPath: 'assets/description/hq_01.png',
            slotName: 'assets/description/hq_01.png',
          ),
        ),
        DescriptionSection(
          id: 'hq-02',
          title: 'Google Calendar와 보드 관리',
          tocTitle: 'Google Calendar',
          eyebrow: '회사 달력, 이벤트 편집, 보드, 칸반',
          summary:
              'Google Calendar를 연동해 관리자 간 일정을 공유하고 보드 또는 칸반 형태의 업무를 관리합니다.',
          paragraphs: const [
            '본사 화면은 회사 달력과 Google Calendar 이벤트를 연결해 일정 확인, 생성, 수정, 완료 이벤트 보기를 지원합니다.',
            '달력 기반 업무는 보드와 칸반 형태로 확장되어 관리자가 진행 상황을 공유하고 정리하는 데 사용됩니다.',
          ],
          bullets: const [
            'Google Calendar 기반 일정 공유를 지원합니다.',
            '보드와 칸반 형태로 업무 진행 상태를 관리합니다.',
            '해당 서비스에 대한 세팅 지원도 패키지에 포함됩니다.',
          ],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: 'Google Calendar와 보드 관리 캡처',
            caption: 'Google Calendar와 보드 관리 화면에 대응하는 캡처 이미지입니다.',
            icon: Icons.event_note_rounded,
            assetPath: 'assets/description/hq_02.jpg',
            slotName: 'assets/description/hq_02.jpg',
          ),
        ),
        DescriptionSection(
          id: 'hq-03',
          title: '출근부와 휴게시간표',
          tocTitle: '근태 서류화',
          eyebrow: '근무자 출퇴근, 휴게시간, Excel 생성',
          summary: '근무자들의 출퇴근과 휴게시간 기록을 관리하고 Excel 문서로 만들어 공유할 수 있습니다.',
          paragraphs: const [
            '관리자는 날짜별, 사용자별 근태 기록을 확인하고 출근부 또는 휴게시간표를 생성할 수 있습니다.',
            '생성된 문서는 메일 발송이나 보관 흐름과 연결되어 현장 기록을 서류화합니다.',
          ],
          bullets: const [
            '출퇴근과 휴게 기록을 관리자 화면에서 확인합니다.',
            'Excel 문서 생성과 메일 발송 흐름을 제공합니다.',
          ],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '출근부와 휴게시간표 캡처',
            caption: '출근부와 휴게시간표 화면에 대응하는 캡처 이미지입니다.',
            icon: Icons.table_chart_rounded,
            assetPath: 'assets/description/hq_03.jpg',
            slotName: 'assets/description/hq_03.jpg',
          ),
        ),
        DescriptionSection(
          id: 'hq-04',
          title: '본사 통계와 리포트',
          tocTitle: '통계 리포트',
          eyebrow: 'A/B 보고서, 날짜별, 요일별, PDF, 차트',
          summary: '운영 데이터를 날짜별·요일별로 분석하고 PDF 또는 차트 리포트 형태로 확인합니다.',
          paragraphs: const [
            '통계 화면은 단순 건수 확인을 넘어 A/B 보고서, 날짜별 심화 통계, 요일별 패턴 분석 같은 관리형 지표를 제공합니다.',
            '필요한 경우 차트와 PDF 리포트로 출력해 회의나 업무 공유 자료로 활용할 수 있습니다.',
          ],
          bullets: const [
            '현장 운영 지표를 날짜와 요일 기준으로 분석합니다.',
            '차트와 PDF 리포트를 생성할 수 있습니다.',
          ],
          layout: DescriptionSectionLayout.portrait,
          media: const DescriptionMediaSpec(
            title: '본사 통계와 리포트 캡처',
            caption: '본사 통계와 리포트 화면에 대응하는 캡처 이미지입니다.',
            icon: Icons.query_stats_rounded,
            assetPath: 'assets/description/hq_04.jpg',
            slotName: 'assets/description/hq_04.jpg',
          ),
        ),
      ],
    ),
    DescriptionChapter(
      id: 'tablet',
      title: '태블릿과 고객 출차 요청',
      summary: '내방객 또는 고객사가 직접 출차 요청을 할 수 있도록 태블릿과 휴대폰에 최적화된 화면을 제공합니다.',
      sections: [
        DescriptionSection(
          id: 'tablet-01',
          title: '큰 패드 모드',
          tocTitle: '큰 패드',
          eyebrow: '출차 요청, 뒤 번호, 검색',
          summary: '큰 태블릿에서 차량번호 뒤 4자리 검색과 출차 요청 현황 시각화를 제공합니다.',
          paragraphs: const [
            '큰 패드 모드는 넓은 가로 화면을 활용해 입력 영역과 현황 표시 영역을 함께 보여줄 수 있습니다.',
            '고객은 번호판 뒤 4자리 등 간단한 정보로 차량을 찾고 출차 요청을 진행합니다.',
          ],
          bullets: const [
            '갤럭시 탭 등 태블릿에서의 사용을 권장합니다.',
          ],
          layout: DescriptionSectionLayout.landscape,
          media: const DescriptionMediaSpec(
            title: '큰 패드 모드 캡처',
            caption: '큰 패드 모드 화면에 대응하는 캡처 이미지입니다.',
            icon: Icons.tablet_mac_rounded,
            assetPath: 'assets/description/tablet_01.png',
            slotName: 'assets/description/tablet_01.png',
          ),
        ),
        DescriptionSection(
          id: 'tablet-02',
          title: '작은 패드 모드',
          tocTitle: '작은 패드',
          eyebrow: '작은 태블릿 최적화',
          summary: '비치된 태블릿 크기가 작을 때도 출차 요청을 사용할 수 있도록 작은 화면에 맞춘 UI를 제공합니다.',
          paragraphs: const [
            '작은 패드 모드는 큰 패드 UI가 부적합한 환경에서 버튼 크기, 정보량, 화면 전환 방식을 조정합니다.',
            '공간이 제한된 안내 데스크나 소형 태블릿에서도 고객 요청 흐름을 유지할 수 있습니다.',
          ],
          bullets: const [
            '갤럭시 탭 등 태블릿에서의 사용을 권장합니다.',
            '특히 작은 구세대 기종 사용에 적합합니다.',
          ],
          layout: DescriptionSectionLayout.landscape,
          media: const DescriptionMediaSpec(
            title: '작은 패드 모드 캡처',
            caption: '작은 패드 모드 화면에 대응하는 캡처 이미지입니다.',
            icon: Icons.tablet_mac_rounded,
            assetPath: 'assets/description/tablet_02.png',
            slotName: 'assets/description/tablet_02.png',
          ),
        ),
        DescriptionSection(
          id: 'tablet-03',
          title: '직접 출차 모드',
          tocTitle: '직접 출차',
          eyebrow: 'VIP, 1:1 고객 관리, 모바일 지원',
          summary: 'VIP 또는 특정 고객사가 직접 출차 요청을 해야 하는 환경을 위해 태블릿과 휴대폰 모두 지원합니다.',
          paragraphs: const [
            '직접 출차 모드는 고객에게 더 간단한 1:1 요청 흐름을 제공해 특정 차량을 빠르게 요청하도록 구성됩니다.',
            '태블릿뿐 아니라 휴대폰에서도 사용할 수 있어 고객 접점에 따라 화면을 선택할 수 있습니다.',
          ],
          bullets: const [
            '핸드폰 사용에 최적화된 UI입니다.',
            'VIP 고객을 관리하는 갑사의 직원 혹은 특정 고객 등 개인 휴대폰 설치에 적합합니다.',
          ],
          layout: DescriptionSectionLayout.landscape,
          media: const DescriptionMediaSpec(
            title: '직접 출차 모드 캡처',
            caption: '직접 출차 모드 화면에 대응하는 캡처 이미지입니다.',
            icon: Icons.touch_app_rounded,
            assetPath: 'assets/description/tablet_03.jpg',
            slotName: 'assets/description/tablet_03.jpg',
          ),
        ),
        DescriptionSection(
          id: 'tablet-04',
          title: '태블릿 2D 맵 모드',
          tocTitle: '태블릿 2D',
          eyebrow: '2D 시각화, 잔여 구역, 출차 요청',
          summary: '태블릿에서 현재 주차 구역별 현황과 잔여 구역을 2D로 보여주고 출차 요청을 지원합니다.',
          paragraphs: const [
            '고객은 단순 번호 검색뿐 아니라 주차 구역 상태를 시각적으로 확인할 수 있습니다.',
            '2D 맵은 고객 안내와 현장 상태 파악을 동시에 제공하는 태블릿 전용 화면으로 사용할 수 있습니다.',
          ],
          bullets: const [
            '고객에게 차량 주차 현황을 시각화하여 대기 장소에 비치하기에 적합합니다.',
          ],
          layout: DescriptionSectionLayout.landscape,
          media: const DescriptionMediaSpec(
            title: '태블릿 2D 맵 모드 캡처',
            caption: '태블릿 2D 맵 모드 화면에 대응하는 캡처 이미지입니다.',
            icon: Icons.map_rounded,
            assetPath: 'assets/description/tablet_04.png',
            slotName: 'assets/description/tablet_04.png',
          ),
        ),
      ],
    ),
  ],
);
