class TutorialPageSpec {
  final String imageAsset;
  final String title;
  final String desc;
  final List<String> bullets;
  final String? warning;
  final String? linkLabel;
  final String? linkRoute;

  const TutorialPageSpec({
    required this.imageAsset,
    required this.title,
    required this.desc,
    this.bullets = const <String>[],
    this.warning,
    this.linkLabel,
    this.linkRoute,
  });
}

const List<TutorialPageSpec> kAppStartFullTutorialPages = [
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/03.png',
    title: '업무 메인 화면',
    desc: '기본적인 셋업 데이터가 필요합니다.',
    bullets: const [
      '"대시보드" 버튼을 눌러 보조 페이지를 통해 근무지에 대한 기본 정보를 핸드폰으로 가져와야 합니다.',
    ],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/04.png',
    title: '대시보드 화면',
    desc: '다른 기능은 추후 직접 눌러보면서 이해하기',
    bullets: const [
      '"보조 페이지 열기"버튼을 눌러 설정 화면을 열어야 합니다.',
      '메모, 앱 테마 설정, 사진 전송, 서류함 열기 기능 등은 이번 튜토리얼에서 설명을 제공하지 않습니다.',
    ],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/05.png',
    title: '데이터 새로고침 버튼과 로그아웃 버튼',
    desc: '데이터 새로고침 버튼은 처음 앱 설치 직후 한 번만 누르면 됩니다.',
    bullets: const [
      '추후 주차 구역 혹은 정산 유형 등에 변화가 생기지 않는 이상 누를 일이 없습니다.',
    ],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/06.png',
    title: '상단의 기능들은 건드리지 말 것',
    desc: '번호판 TTS 관련 On/Off 기능입니다.',
    bullets: const [
      '상위 지시자의 오더 없이 손대지 않는 것을 권장합니다.',
    ],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/07.png',
    title: '근무지의 주차 구역',
    desc: '주차 구역 별 주차 현황을 제자리에서 확인이 가능합니다.',
    bullets: const [
      '주차 구역이 2곳 이상일 경우 좌우 스와이프 혹은 "층 선택" 버튼으로 타 구역으로 화면을 전환할 수 있습니다.',
      '이제 하단의 "생성" 버튼을 누르면 번호판 데이터 삽입 페이지로 전환합니다.',
    ],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/08.png',
    title: '번호판 입력 화면',
    desc: 'OCR을 사용하거나 직접 수기로 입력할 수 있습니다.',
    bullets: const [
      '이전 화면으로 돌아가려면 상단의 "뒤로 가기"를 눌러야 합니다.',
      '차량에 대한 스크래치 등의 사진을 촬영할 수 있습니다.',
      '상태 메모를 했을 경우 메모했던 차량에 대한 정보가 한 번 더 출력됩니다.',
    ],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/09.png',
    title: '번호판 입력에 오류도 발생합니다.',
    desc: '사진과 같이 번호판 데이터가 비정상적으로 삽입되는 경우도 있습니다.',
    bullets: const [
      '하단에서 수정하고자 하는 각각의 앞, 중간, 뒷자리를 선택합니다.',
    ],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/10.png',
    title: '번호판 수정 화면',
    desc: '앞자리의 두자리 혹은 세자리 여부도 수정이 가능합니다.',
    bullets: const [
      '각각의 앞, 중간, 뒷자리를 선택하여 수정이 가능합니다.',
    ],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/11.png',
    title: '입차 요청 혹은 입차 완료',
    desc: '앞자리의 두자리 혹은 세자리 여부도 수정이 가능합니다.',
    bullets: const [
      '업무 프로세스에 따라 입차 요청 기능이 없는 경우도 있습니다.',
      '정산 유형과 상태 메모 관련 튜토리얼은 이번 목차에서 제공하지 않습니다.',
      '이번에는 주차 구역을 삽입하기 위해 "주차 구역 선택" 버튼을 선택합니다.',
    ],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/12.png',
    title: '부모 주차 구역 선택 화면',
    desc: '지하 1층? 지하 2층?',
    bullets: const [
      '차량의 위치가 지하 1층인지 지하 2층인지 선택하는 화면입니다.',
    ],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/13.png',
    title: '자식 주차 구역 선택 화면',
    desc: '주차 구역 A? B?',
    bullets: const [
      '사전에 정의된 상세 주차 구역을 선택하는 화면입니다.',
    ],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/14.png',
    title: '최종 주차 구역선택',
    desc: '어디에 주차했는지',
    bullets: const [
      '사전에 정의된 상세 주차 구역을 선택하는 화면입니다.',
    ],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/15.png',
    title: '페이지 15',
    desc: '설명 문구를 여기에 작성하세요. (이미지: 15)',
    bullets: const <String>[],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/16.png',
    title: '페이지 16',
    desc: '설명 문구를 여기에 작성하세요. (이미지: 16)',
    bullets: const <String>[],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/17.png',
    title: '페이지 17',
    desc: '설명 문구를 여기에 작성하세요. (이미지: 17)',
    bullets: const <String>[],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/18.png',
    title: '페이지 18',
    desc: '설명 문구를 여기에 작성하세요. (이미지: 18)',
    bullets: const <String>[],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/19.png',
    title: '페이지 19',
    desc: '설명 문구를 여기에 작성하세요. (이미지: 19)',
    bullets: const <String>[],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/20.png',
    title: '페이지 20',
    desc: '설명 문구를 여기에 작성하세요. (이미지: 20)',
    bullets: const <String>[],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/21.png',
    title: '페이지 21',
    desc: '설명 문구를 여기에 작성하세요. (이미지: 21)',
    bullets: const <String>[],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/22.png',
    title: '페이지 22',
    desc: '설명 문구를 여기에 작성하세요. (이미지: 22)',
    bullets: const <String>[],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/23.png',
    title: '페이지 23',
    desc: '설명 문구를 여기에 작성하세요. (이미지: 23)',
    bullets: const <String>[],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/24.png',
    title: '페이지 24',
    desc: '설명 문구를 여기에 작성하세요. (이미지: 24)',
    bullets: const <String>[],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/25.png',
    title: '페이지 25',
    desc: '설명 문구를 여기에 작성하세요. (이미지: 25)',
    bullets: const <String>[],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/26.png',
    title: '페이지 26',
    desc: '설명 문구를 여기에 작성하세요. (이미지: 26)',
    bullets: const <String>[],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/27.png',
    title: '페이지 27',
    desc: '설명 문구를 여기에 작성하세요. (이미지: 27)',
    bullets: const <String>[],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/28.png',
    title: '페이지 28',
    desc: '설명 문구를 여기에 작성하세요. (이미지: 28)',
    bullets: const <String>[],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/29.png',
    title: '페이지 29',
    desc: '설명 문구를 여기에 작성하세요. (이미지: 29)',
    bullets: const <String>[],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/30.png',
    title: '페이지 30',
    desc: '설명 문구를 여기에 작성하세요. (이미지: 30)',
    bullets: const <String>[],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/31.png',
    title: '페이지 31',
    desc: '설명 문구를 여기에 작성하세요. (이미지: 31)',
    bullets: const <String>[],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/32.png',
    title: '페이지 32',
    desc: '설명 문구를 여기에 작성하세요. (이미지: 32)',
    bullets: const <String>[],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/33.png',
    title: '페이지 33',
    desc: '설명 문구를 여기에 작성하세요. (이미지: 33)',
    bullets: const <String>[],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/34.png',
    title: '페이지 34',
    desc: '설명 문구를 여기에 작성하세요. (이미지: 34)',
    bullets: const <String>[],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/35.png',
    title: '페이지 35',
    desc: '설명 문구를 여기에 작성하세요. (이미지: 35)',
    bullets: const <String>[],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/36.png',
    title: '페이지 36',
    desc: '설명 문구를 여기에 작성하세요. (이미지: 36)',
    bullets: const <String>[],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/37.png',
    title: '페이지 37',
    desc: '설명 문구를 여기에 작성하세요. (이미지: 37)',
    bullets: const <String>[],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/38.png',
    title: '페이지 38',
    desc: '설명 문구를 여기에 작성하세요. (이미지: 38)',
    bullets: const <String>[],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/39.png',
    title: '페이지 39',
    desc: '설명 문구를 여기에 작성하세요. (이미지: 39)',
    bullets: const <String>[],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
  TutorialPageSpec(
    imageAsset: 'assets/tutorial/40.png',
    title: '마지막 페이지',
    desc: '확인으로 이동합니다.',
    bullets: const ['내용을 점검한 뒤 확인으로 이동하세요'],
    warning: null,
    linkLabel: null,
    linkRoute: null,
  ),
];
